apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  dependsOn:
    - name: policies
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: openshift-platform-team
  path: ./tenants/production
  prune: true
  validation: client
